### ISSUE TITLE
ERROR: CIGAR strings starting with insertion are not supported.

### ISSUE THREAD

**Issue by dannyrabiz** [annalam/mutato#1]
I keep getting this error when running BAM files aligned with BWA. Is there another alignment tool I should be using?

**Comment by annalam** [comment]
Thank you for reporting the issue! We had previously only been using Mutato on BAM files that had been aligned using Bowtie2, which does not generate BAM records where the CIGAR string starts with an insertion. However, a colleague also  recently reported that BWA alignments do sometimes contain such CIGAR strings.

I just released version 0.9 of Mutato, which includes a quick workaround for this issue (along with other new features). Mutato 0.9 now silently ignores the (rare) BAM records that start with an insertion. The ideal solution would be to allow such BAM records to be counted normally, but that will require slightly wider changes to the code (in the current design these indels would need to be written at position -1 of the pileup vector).

**Comment by dannyrabiz** [comment]
Thanks for the quick response! I noticed after I posted the issue that in your Nature paper you used bowtie2 so I was just about to try that. I'll give  version 0.9 a try and let you know how it works.

**Comment by dannyrabiz** [comment]
v0.9 worked great!
